Inject disk size dynamically
ironcore-dev/ceph-provider pull request #428
Opened 2023-12-14 05:30 UTC by ushabelgur

# Proposed Changes

-  Inject disk size dynamically  by checking the disk being attached to ceph cluster

Fixes #406

2023-12-14 11:31 UTC, lukasfrank commented
`ceph df -f json ` might also be helpful to get the ceph info like this: 

```
...
  "stats": {
    "total_bytes": 456005267750912,
    "total_avail_bytes": 455071242383360,
    "total_used_bytes": 934025367552,
    "total_used_raw_bytes": 934025367552,
    "total_used_raw_ratio": 0.0020482775289565325,
    "num_osds": 38,
    "num_per_pool_osds": 38,
    "num_per_pool_omap_osds": 38
  },
...
```

2023-12-18 16:01 UTC, afritzler requested changes

2023-12-18 16:01 UTC, afritzler commented on .github/workflows/integration-test.yml
> +          # sudo umount /mnt
Can you please remove the commented out line. Otherwise the PR looks good.

2023-12-19 07:47 UTC, lukasfrank approved these changes

2023-12-19 07:53 UTC, merged