Fixed OMAP store race condition issue
ironcore-dev/ceph-provider pull request #540
Opened 2024-05-24 04:52 UTC by pradumnapandit

Fixes https://github.com/ironcore-dev/ceph-provider/issues/461

2024-05-28 08:56 UTC, lukasfrank requested changes

2024-05-28 08:56 UTC, lukasfrank commented on internal/omap/omap.go
>  	//Todo: update version
Can you please remove this todo?

2024-05-28 10:08 UTC, pradumnapandit commented on internal/omap/omap.go
>  	//Todo: update version
Removed Todo.

2024-05-29 08:52 UTC, lukasfrank approved these changes

2024-05-29 08:53 UTC, merged